package dev.duardo.neotransfer.core

data class TerritoryProvince(val code: String, val name: String)
data class TerritoryMunicipality(val code: String, val provinceCode: String, val name: String)

/** Factual territory catalog from APK 1.260416 assets/dpabulevar.json. */
object TerritoryCatalog {
    val provinces: List<TerritoryProvince> = listOf(
        TerritoryProvince("21", "Pinar del Río"),
        TerritoryProvince("22", "Artemisa"),
        TerritoryProvince("23", "La Habana"),
        TerritoryProvince("24", "Mayabeque"),
        TerritoryProvince("25", "Matanzas"),
        TerritoryProvince("26", "Villa Clara"),
        TerritoryProvince("27", "Cienfuegos"),
        TerritoryProvince("28", "Sancti Spíritus"),
        TerritoryProvince("29", "Ciego de Ávila"),
        TerritoryProvince("30", "Camagüey"),
        TerritoryProvince("31", "Las Tunas"),
        TerritoryProvince("32", "Holguín"),
        TerritoryProvince("33", "Granma"),
        TerritoryProvince("34", "Santiago de Cuba"),
        TerritoryProvince("35", "Guantánamo"),
        TerritoryProvince("40", "Isla de la Juventud"),
    )
    private val municipalities: List<TerritoryMunicipality> = listOf(
        TerritoryMunicipality("2101", "21", "Sandino"),
        TerritoryMunicipality("2102", "21", "Mantua"),
        TerritoryMunicipality("2103", "21", "Minas de Matahambre"),
        TerritoryMunicipality("2104", "21", "Viñales"),
        TerritoryMunicipality("2105", "21", "La Palma"),
        TerritoryMunicipality("2106", "21", "Los Palacios"),
        TerritoryMunicipality("2107", "21", "Consolación del Sur"),
        TerritoryMunicipality("2108", "21", "Pinar del Río"),
        TerritoryMunicipality("2109", "21", "San Luis"),
        TerritoryMunicipality("2110", "21", "San Juan y Martínez"),
        TerritoryMunicipality("2111", "21", "Guane"),
        TerritoryMunicipality("2201", "22", "Bahía Honda"),
        TerritoryMunicipality("2202", "22", "Mariel"),
        TerritoryMunicipality("2203", "22", "Guanajay"),
        TerritoryMunicipality("2204", "22", "Caimito"),
        TerritoryMunicipality("2205", "22", "Bauta"),
        TerritoryMunicipality("2206", "22", "San Antonio de los Baños"),
        TerritoryMunicipality("2207", "22", "Güira de Melena"),
        TerritoryMunicipality("2208", "22", "Alquízar"),
        TerritoryMunicipality("2209", "22", "Artemisa"),
        TerritoryMunicipality("2210", "22", "Candelaria"),
        TerritoryMunicipality("2211", "22", "San Cristóbal"),
        TerritoryMunicipality("2301", "23", "Playa"),
        TerritoryMunicipality("2302", "23", "Plaza de la Revolución"),
        TerritoryMunicipality("2303", "23", "Centro Habana"),
        TerritoryMunicipality("2304", "23", "Habana Vieja"),
        TerritoryMunicipality("2305", "23", "Regla"),
        TerritoryMunicipality("2306", "23", "Habana del Este"),
        TerritoryMunicipality("2307", "23", "Guanabacoa"),
        TerritoryMunicipality("2308", "23", "San Miguel del Padrón"),
        TerritoryMunicipality("2309", "23", "Diez de Octubre"),
        TerritoryMunicipality("2310", "23", "Cerro"),
        TerritoryMunicipality("2311", "23", "Marianao"),
        TerritoryMunicipality("2312", "23", "La Lisa"),
        TerritoryMunicipality("2313", "23", "Boyeros"),
        TerritoryMunicipality("2314", "23", "Arroyo Naranjo"),
        TerritoryMunicipality("2315", "23", "Cotorro"),
        TerritoryMunicipality("2401", "24", "Bejucal"),
        TerritoryMunicipality("2402", "24", "San José de las Lajas"),
        TerritoryMunicipality("2403", "24", "Jaruco"),
        TerritoryMunicipality("2404", "24", "Santa Cruz del Norte"),
        TerritoryMunicipality("2405", "24", "Madruga"),
        TerritoryMunicipality("2406", "24", "Nueva Paz"),
        TerritoryMunicipality("2407", "24", "San Nicolás"),
        TerritoryMunicipality("2408", "24", "Güines"),
        TerritoryMunicipality("2409", "24", "Melena del Sur"),
        TerritoryMunicipality("2410", "24", "Batabanó"),
        TerritoryMunicipality("2411", "24", "Quivicán"),
        TerritoryMunicipality("2501", "25", "Matanzas"),
        TerritoryMunicipality("2502", "25", "Cárdenas"),
        TerritoryMunicipality("2503", "25", "Martí"),
        TerritoryMunicipality("2504", "25", "Colón"),
        TerritoryMunicipality("2505", "25", "Perico"),
        TerritoryMunicipality("2506", "25", "Jovellanos"),
        TerritoryMunicipality("2507", "25", "Pedro Betancourt"),
        TerritoryMunicipality("2508", "25", "Limonar"),
        TerritoryMunicipality("2509", "25", "Unión de Reyes"),
        TerritoryMunicipality("2510", "25", "Ciénaga de Zapata"),
        TerritoryMunicipality("2511", "25", "Jagüey Grande"),
        TerritoryMunicipality("2512", "25", "Calimete"),
        TerritoryMunicipality("2513", "25", "Los Arabos"),
        TerritoryMunicipality("2601", "26", "Corralillo"),
        TerritoryMunicipality("2602", "26", "Quemado de Güines"),
        TerritoryMunicipality("2603", "26", "Sagua la Grande"),
        TerritoryMunicipality("2604", "26", "Encrucijada"),
        TerritoryMunicipality("2605", "26", "Camajuaní"),
        TerritoryMunicipality("2606", "26", "Caibarién"),
        TerritoryMunicipality("2607", "26", "Remedios"),
        TerritoryMunicipality("2608", "26", "Placetas"),
        TerritoryMunicipality("2609", "26", "Santa Clara"),
        TerritoryMunicipality("2610", "26", "Cifuentes"),
        TerritoryMunicipality("2611", "26", "Santo Domingo"),
        TerritoryMunicipality("2612", "26", "Ranchuelo"),
        TerritoryMunicipality("2613", "26", "Manicaragua"),
        TerritoryMunicipality("2701", "27", "Aguada de Pasajeros"),
        TerritoryMunicipality("2702", "27", "Rodas"),
        TerritoryMunicipality("2703", "27", "Palmira"),
        TerritoryMunicipality("2704", "27", "Lajas"),
        TerritoryMunicipality("2705", "27", "Cruces"),
        TerritoryMunicipality("2706", "27", "Cumanayagua"),
        TerritoryMunicipality("2707", "27", "Cienfuegos"),
        TerritoryMunicipality("2708", "27", "Abreus"),
        TerritoryMunicipality("2801", "28", "Yaguajay"),
        TerritoryMunicipality("2802", "28", "Jatibonico"),
        TerritoryMunicipality("2803", "28", "Taguasco"),
        TerritoryMunicipality("2804", "28", "Cabaiguán"),
        TerritoryMunicipality("2805", "28", "Fomento"),
        TerritoryMunicipality("2806", "28", "Trinidad"),
        TerritoryMunicipality("2807", "28", "Sancti Spíritus"),
        TerritoryMunicipality("2808", "28", "La Sierpe"),
        TerritoryMunicipality("2901", "29", "Chambas"),
        TerritoryMunicipality("2902", "29", "Morón"),
        TerritoryMunicipality("2903", "29", "Bolivia"),
        TerritoryMunicipality("2904", "29", "Primero de Enero"),
        TerritoryMunicipality("2905", "29", "Ciro Redondo"),
        TerritoryMunicipality("2906", "29", "Florencia"),
        TerritoryMunicipality("2907", "29", "Majagua"),
        TerritoryMunicipality("2908", "29", "Ciego de Ávila"),
        TerritoryMunicipality("2909", "29", "Venezuela"),
        TerritoryMunicipality("2910", "29", "Baraguá"),
        TerritoryMunicipality("3001", "30", "Carlos Manuel de Céspedes"),
        TerritoryMunicipality("3002", "30", "Esmeralda"),
        TerritoryMunicipality("3003", "30", "Sierra de Cubitas"),
        TerritoryMunicipality("3004", "30", "Minas"),
        TerritoryMunicipality("3005", "30", "Nuevitas"),
        TerritoryMunicipality("3006", "30", "Guáimaro"),
        TerritoryMunicipality("3007", "30", "Sibanicú"),
        TerritoryMunicipality("3008", "30", "Camagüey"),
        TerritoryMunicipality("3009", "30", "Florida"),
        TerritoryMunicipality("3010", "30", "Vertientes"),
        TerritoryMunicipality("3011", "30", "Jimaguayú"),
        TerritoryMunicipality("3012", "30", "Najasa"),
        TerritoryMunicipality("3013", "30", "Santa Cruz del Sur"),
        TerritoryMunicipality("3101", "31", "Manatí"),
        TerritoryMunicipality("3102", "31", "Puerto Padre"),
        TerritoryMunicipality("3103", "31", "Jesús Menéndez"),
        TerritoryMunicipality("3104", "31", "Majibacoa"),
        TerritoryMunicipality("3105", "31", "Las Tunas"),
        TerritoryMunicipality("3106", "31", "Jobabo"),
        TerritoryMunicipality("3107", "31", "Colombia"),
        TerritoryMunicipality("3108", "31", "Amancio"),
        TerritoryMunicipality("3201", "32", "Gibara"),
        TerritoryMunicipality("3202", "32", "Rafael Freire"),
        TerritoryMunicipality("3203", "32", "Banes"),
        TerritoryMunicipality("3204", "32", "Antilla"),
        TerritoryMunicipality("3205", "32", "Báguanos"),
        TerritoryMunicipality("3206", "32", "Holguín"),
        TerritoryMunicipality("3207", "32", "Calixto García"),
        TerritoryMunicipality("3208", "32", "Cacocum"),
        TerritoryMunicipality("3209", "32", "Urbano Noris"),
        TerritoryMunicipality("3210", "32", "Cueto"),
        TerritoryMunicipality("3211", "32", "Mayarí"),
        TerritoryMunicipality("3212", "32", "Frank País"),
        TerritoryMunicipality("3213", "32", "Sagua de Tánamo"),
        TerritoryMunicipality("3214", "32", "Moa"),
        TerritoryMunicipality("3301", "33", "Río Cauto"),
        TerritoryMunicipality("3302", "33", "Cauto Cristo"),
        TerritoryMunicipality("3303", "33", "Jiguaní"),
        TerritoryMunicipality("3304", "33", "Bayamo"),
        TerritoryMunicipality("3305", "33", "Yara"),
        TerritoryMunicipality("3306", "33", "Manzanillo"),
        TerritoryMunicipality("3307", "33", "Campechuela"),
        TerritoryMunicipality("3308", "33", "Media Luna"),
        TerritoryMunicipality("3309", "33", "Niquero"),
        TerritoryMunicipality("3310", "33", "Pilón"),
        TerritoryMunicipality("3311", "33", "Bartolomé Masó"),
        TerritoryMunicipality("3312", "33", "Buey Arriba"),
        TerritoryMunicipality("3313", "33", "Guisa"),
        TerritoryMunicipality("3401", "34", "Contramaestre"),
        TerritoryMunicipality("3402", "34", "Mella"),
        TerritoryMunicipality("3403", "34", "San Luis"),
        TerritoryMunicipality("3404", "34", "Segundo Frente"),
        TerritoryMunicipality("3405", "34", "Songo La Maya"),
        TerritoryMunicipality("3406", "34", "Santiago de Cuba"),
        TerritoryMunicipality("3407", "34", "Palma Soriano"),
        TerritoryMunicipality("3408", "34", "Tercer Frente"),
        TerritoryMunicipality("3409", "34", "Guamá"),
        TerritoryMunicipality("3501", "35", "El Salvador"),
        TerritoryMunicipality("3502", "35", "Manuel Tames"),
        TerritoryMunicipality("3503", "35", "Yateras"),
        TerritoryMunicipality("3504", "35", "Baracoa"),
        TerritoryMunicipality("3505", "35", "Maisí"),
        TerritoryMunicipality("3506", "35", "Imías"),
        TerritoryMunicipality("3507", "35", "San Antonio del Sur"),
        TerritoryMunicipality("3508", "35", "Caimanera"),
        TerritoryMunicipality("3509", "35", "Guantánamo"),
        TerritoryMunicipality("3510", "35", "Niceto Pérez"),
        TerritoryMunicipality("4001", "40", "Isla de la Juventud"),
    )

    fun municipalities(provinceCode: String): List<TerritoryMunicipality> = municipalities.filter { it.provinceCode == provinceCode }

    /** Responses may contain a two-digit municipal component or its four-digit DPA. */
    fun normalizeMunicipality(provinceCode: String, municipalityCode: String): String? {
        val code = if (municipalityCode.length == 2) provinceCode + municipalityCode else municipalityCode
        return municipalities.firstOrNull { it.provinceCode == provinceCode && it.code == code }?.code
    }
}
